apiVersion: v1
kind: Service
metadata:
  name: grpc-beer-service
spec:
  selector:
    app: grpc-beer-service
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - protocol: TCP
      port: 9090
      targetPort: grpc
